// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WirelessHid.proto

package com.baniel.wirelesshid;

public final class WirelessHidProto {
  private WirelessHidProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface HidDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:HidData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .HidData.DataType type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required .HidData.DataType type = 1;</code>
     */
    com.baniel.wirelesshid.WirelessHidProto.HidData.DataType getType();

    /**
     * <code>optional int32 x_shift = 2;</code>
     */
    boolean hasXShift();
    /**
     * <code>optional int32 x_shift = 2;</code>
     */
    int getXShift();

    /**
     * <code>optional int32 y_shift = 3;</code>
     */
    boolean hasYShift();
    /**
     * <code>optional int32 y_shift = 3;</code>
     */
    int getYShift();

    /**
     * <code>optional int32 mouse_key_value = 4;</code>
     */
    boolean hasMouseKeyValue();
    /**
     * <code>optional int32 mouse_key_value = 4;</code>
     */
    int getMouseKeyValue();

    /**
     * <code>optional int32 mouse_scroll = 5;</code>
     */
    boolean hasMouseScroll();
    /**
     * <code>optional int32 mouse_scroll = 5;</code>
     */
    int getMouseScroll();

    /**
     * <code>optional int32 keyboard_value = 6;</code>
     */
    boolean hasKeyboardValue();
    /**
     * <code>optional int32 keyboard_value = 6;</code>
     */
    int getKeyboardValue();
  }
  /**
   * Protobuf type {@code HidData}
   */
  public static final class HidData extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:HidData)
      HidDataOrBuilder {
    // Use HidData.newBuilder() to construct.
    private HidData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private HidData(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final HidData defaultInstance;
    public static HidData getDefaultInstance() {
      return defaultInstance;
    }

    public HidData getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private HidData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.baniel.wirelesshid.WirelessHidProto.HidData.DataType value = com.baniel.wirelesshid.WirelessHidProto.HidData.DataType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              xShift_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              yShift_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              mouseKeyValue_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              mouseScroll_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              keyboardValue_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.baniel.wirelesshid.WirelessHidProto.internal_static_HidData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.baniel.wirelesshid.WirelessHidProto.internal_static_HidData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.baniel.wirelesshid.WirelessHidProto.HidData.class, com.baniel.wirelesshid.WirelessHidProto.HidData.Builder.class);
    }

    public static com.google.protobuf.Parser<HidData> PARSER =
        new com.google.protobuf.AbstractParser<HidData>() {
      public HidData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HidData(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<HidData> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code HidData.DataType}
     */
    public enum DataType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>MOUSE_MOVE = 0;</code>
       */
      MOUSE_MOVE(0, 0),
      /**
       * <code>MOUSE_CLICK_PRESS = 1;</code>
       */
      MOUSE_CLICK_PRESS(1, 1),
      /**
       * <code>MOUSE_CLICK_RELEASE = 2;</code>
       */
      MOUSE_CLICK_RELEASE(2, 2),
      /**
       * <code>MOUSE_SCROLL = 3;</code>
       */
      MOUSE_SCROLL(3, 3),
      /**
       * <code>KEYBOARD_LONG_PRESS = 4;</code>
       */
      KEYBOARD_LONG_PRESS(4, 4),
      /**
       * <code>KEYBOARD_LONG_RELEASE = 5;</code>
       */
      KEYBOARD_LONG_RELEASE(5, 5),
      /**
       * <code>KEYBOARD_HIT = 6;</code>
       */
      KEYBOARD_HIT(6, 6),
      ;

      /**
       * <code>MOUSE_MOVE = 0;</code>
       */
      public static final int MOUSE_MOVE_VALUE = 0;
      /**
       * <code>MOUSE_CLICK_PRESS = 1;</code>
       */
      public static final int MOUSE_CLICK_PRESS_VALUE = 1;
      /**
       * <code>MOUSE_CLICK_RELEASE = 2;</code>
       */
      public static final int MOUSE_CLICK_RELEASE_VALUE = 2;
      /**
       * <code>MOUSE_SCROLL = 3;</code>
       */
      public static final int MOUSE_SCROLL_VALUE = 3;
      /**
       * <code>KEYBOARD_LONG_PRESS = 4;</code>
       */
      public static final int KEYBOARD_LONG_PRESS_VALUE = 4;
      /**
       * <code>KEYBOARD_LONG_RELEASE = 5;</code>
       */
      public static final int KEYBOARD_LONG_RELEASE_VALUE = 5;
      /**
       * <code>KEYBOARD_HIT = 6;</code>
       */
      public static final int KEYBOARD_HIT_VALUE = 6;


      public final int getNumber() { return value; }

      public static DataType valueOf(int value) {
        switch (value) {
          case 0: return MOUSE_MOVE;
          case 1: return MOUSE_CLICK_PRESS;
          case 2: return MOUSE_CLICK_RELEASE;
          case 3: return MOUSE_SCROLL;
          case 4: return KEYBOARD_LONG_PRESS;
          case 5: return KEYBOARD_LONG_RELEASE;
          case 6: return KEYBOARD_HIT;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<DataType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<DataType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<DataType>() {
              public DataType findValueByNumber(int number) {
                return DataType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.baniel.wirelesshid.WirelessHidProto.HidData.getDescriptor().getEnumTypes().get(0);
      }

      private static final DataType[] VALUES = values();

      public static DataType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private DataType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:HidData.DataType)
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private com.baniel.wirelesshid.WirelessHidProto.HidData.DataType type_;
    /**
     * <code>required .HidData.DataType type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .HidData.DataType type = 1;</code>
     */
    public com.baniel.wirelesshid.WirelessHidProto.HidData.DataType getType() {
      return type_;
    }

    public static final int X_SHIFT_FIELD_NUMBER = 2;
    private int xShift_;
    /**
     * <code>optional int32 x_shift = 2;</code>
     */
    public boolean hasXShift() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 x_shift = 2;</code>
     */
    public int getXShift() {
      return xShift_;
    }

    public static final int Y_SHIFT_FIELD_NUMBER = 3;
    private int yShift_;
    /**
     * <code>optional int32 y_shift = 3;</code>
     */
    public boolean hasYShift() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 y_shift = 3;</code>
     */
    public int getYShift() {
      return yShift_;
    }

    public static final int MOUSE_KEY_VALUE_FIELD_NUMBER = 4;
    private int mouseKeyValue_;
    /**
     * <code>optional int32 mouse_key_value = 4;</code>
     */
    public boolean hasMouseKeyValue() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 mouse_key_value = 4;</code>
     */
    public int getMouseKeyValue() {
      return mouseKeyValue_;
    }

    public static final int MOUSE_SCROLL_FIELD_NUMBER = 5;
    private int mouseScroll_;
    /**
     * <code>optional int32 mouse_scroll = 5;</code>
     */
    public boolean hasMouseScroll() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int32 mouse_scroll = 5;</code>
     */
    public int getMouseScroll() {
      return mouseScroll_;
    }

    public static final int KEYBOARD_VALUE_FIELD_NUMBER = 6;
    private int keyboardValue_;
    /**
     * <code>optional int32 keyboard_value = 6;</code>
     */
    public boolean hasKeyboardValue() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional int32 keyboard_value = 6;</code>
     */
    public int getKeyboardValue() {
      return keyboardValue_;
    }

    private void initFields() {
      type_ = com.baniel.wirelesshid.WirelessHidProto.HidData.DataType.MOUSE_MOVE;
      xShift_ = 0;
      yShift_ = 0;
      mouseKeyValue_ = 0;
      mouseScroll_ = 0;
      keyboardValue_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, xShift_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, yShift_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, mouseKeyValue_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, mouseScroll_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, keyboardValue_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, xShift_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, yShift_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, mouseKeyValue_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, mouseScroll_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, keyboardValue_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.baniel.wirelesshid.WirelessHidProto.HidData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.baniel.wirelesshid.WirelessHidProto.HidData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.baniel.wirelesshid.WirelessHidProto.HidData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.baniel.wirelesshid.WirelessHidProto.HidData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.baniel.wirelesshid.WirelessHidProto.HidData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.baniel.wirelesshid.WirelessHidProto.HidData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.baniel.wirelesshid.WirelessHidProto.HidData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.baniel.wirelesshid.WirelessHidProto.HidData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.baniel.wirelesshid.WirelessHidProto.HidData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.baniel.wirelesshid.WirelessHidProto.HidData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.baniel.wirelesshid.WirelessHidProto.HidData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HidData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:HidData)
        com.baniel.wirelesshid.WirelessHidProto.HidDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.baniel.wirelesshid.WirelessHidProto.internal_static_HidData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.baniel.wirelesshid.WirelessHidProto.internal_static_HidData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.baniel.wirelesshid.WirelessHidProto.HidData.class, com.baniel.wirelesshid.WirelessHidProto.HidData.Builder.class);
      }

      // Construct using com.baniel.wirelesshid.WirelessHidProto.HidData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = com.baniel.wirelesshid.WirelessHidProto.HidData.DataType.MOUSE_MOVE;
        bitField0_ = (bitField0_ & ~0x00000001);
        xShift_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        yShift_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        mouseKeyValue_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        mouseScroll_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        keyboardValue_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.baniel.wirelesshid.WirelessHidProto.internal_static_HidData_descriptor;
      }

      public com.baniel.wirelesshid.WirelessHidProto.HidData getDefaultInstanceForType() {
        return com.baniel.wirelesshid.WirelessHidProto.HidData.getDefaultInstance();
      }

      public com.baniel.wirelesshid.WirelessHidProto.HidData build() {
        com.baniel.wirelesshid.WirelessHidProto.HidData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.baniel.wirelesshid.WirelessHidProto.HidData buildPartial() {
        com.baniel.wirelesshid.WirelessHidProto.HidData result = new com.baniel.wirelesshid.WirelessHidProto.HidData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.xShift_ = xShift_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.yShift_ = yShift_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.mouseKeyValue_ = mouseKeyValue_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.mouseScroll_ = mouseScroll_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.keyboardValue_ = keyboardValue_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.baniel.wirelesshid.WirelessHidProto.HidData) {
          return mergeFrom((com.baniel.wirelesshid.WirelessHidProto.HidData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.baniel.wirelesshid.WirelessHidProto.HidData other) {
        if (other == com.baniel.wirelesshid.WirelessHidProto.HidData.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasXShift()) {
          setXShift(other.getXShift());
        }
        if (other.hasYShift()) {
          setYShift(other.getYShift());
        }
        if (other.hasMouseKeyValue()) {
          setMouseKeyValue(other.getMouseKeyValue());
        }
        if (other.hasMouseScroll()) {
          setMouseScroll(other.getMouseScroll());
        }
        if (other.hasKeyboardValue()) {
          setKeyboardValue(other.getKeyboardValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.baniel.wirelesshid.WirelessHidProto.HidData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.baniel.wirelesshid.WirelessHidProto.HidData) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.baniel.wirelesshid.WirelessHidProto.HidData.DataType type_ = com.baniel.wirelesshid.WirelessHidProto.HidData.DataType.MOUSE_MOVE;
      /**
       * <code>required .HidData.DataType type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .HidData.DataType type = 1;</code>
       */
      public com.baniel.wirelesshid.WirelessHidProto.HidData.DataType getType() {
        return type_;
      }
      /**
       * <code>required .HidData.DataType type = 1;</code>
       */
      public Builder setType(com.baniel.wirelesshid.WirelessHidProto.HidData.DataType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .HidData.DataType type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = com.baniel.wirelesshid.WirelessHidProto.HidData.DataType.MOUSE_MOVE;
        onChanged();
        return this;
      }

      private int xShift_ ;
      /**
       * <code>optional int32 x_shift = 2;</code>
       */
      public boolean hasXShift() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 x_shift = 2;</code>
       */
      public int getXShift() {
        return xShift_;
      }
      /**
       * <code>optional int32 x_shift = 2;</code>
       */
      public Builder setXShift(int value) {
        bitField0_ |= 0x00000002;
        xShift_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 x_shift = 2;</code>
       */
      public Builder clearXShift() {
        bitField0_ = (bitField0_ & ~0x00000002);
        xShift_ = 0;
        onChanged();
        return this;
      }

      private int yShift_ ;
      /**
       * <code>optional int32 y_shift = 3;</code>
       */
      public boolean hasYShift() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 y_shift = 3;</code>
       */
      public int getYShift() {
        return yShift_;
      }
      /**
       * <code>optional int32 y_shift = 3;</code>
       */
      public Builder setYShift(int value) {
        bitField0_ |= 0x00000004;
        yShift_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 y_shift = 3;</code>
       */
      public Builder clearYShift() {
        bitField0_ = (bitField0_ & ~0x00000004);
        yShift_ = 0;
        onChanged();
        return this;
      }

      private int mouseKeyValue_ ;
      /**
       * <code>optional int32 mouse_key_value = 4;</code>
       */
      public boolean hasMouseKeyValue() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 mouse_key_value = 4;</code>
       */
      public int getMouseKeyValue() {
        return mouseKeyValue_;
      }
      /**
       * <code>optional int32 mouse_key_value = 4;</code>
       */
      public Builder setMouseKeyValue(int value) {
        bitField0_ |= 0x00000008;
        mouseKeyValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 mouse_key_value = 4;</code>
       */
      public Builder clearMouseKeyValue() {
        bitField0_ = (bitField0_ & ~0x00000008);
        mouseKeyValue_ = 0;
        onChanged();
        return this;
      }

      private int mouseScroll_ ;
      /**
       * <code>optional int32 mouse_scroll = 5;</code>
       */
      public boolean hasMouseScroll() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 mouse_scroll = 5;</code>
       */
      public int getMouseScroll() {
        return mouseScroll_;
      }
      /**
       * <code>optional int32 mouse_scroll = 5;</code>
       */
      public Builder setMouseScroll(int value) {
        bitField0_ |= 0x00000010;
        mouseScroll_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 mouse_scroll = 5;</code>
       */
      public Builder clearMouseScroll() {
        bitField0_ = (bitField0_ & ~0x00000010);
        mouseScroll_ = 0;
        onChanged();
        return this;
      }

      private int keyboardValue_ ;
      /**
       * <code>optional int32 keyboard_value = 6;</code>
       */
      public boolean hasKeyboardValue() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional int32 keyboard_value = 6;</code>
       */
      public int getKeyboardValue() {
        return keyboardValue_;
      }
      /**
       * <code>optional int32 keyboard_value = 6;</code>
       */
      public Builder setKeyboardValue(int value) {
        bitField0_ |= 0x00000020;
        keyboardValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 keyboard_value = 6;</code>
       */
      public Builder clearKeyboardValue() {
        bitField0_ = (bitField0_ & ~0x00000020);
        keyboardValue_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:HidData)
    }

    static {
      defaultInstance = new HidData(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:HidData)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HidData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_HidData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021WirelessHid.proto\"\270\002\n\007HidData\022\037\n\004type\030" +
      "\001 \002(\0162\021.HidData.DataType\022\017\n\007x_shift\030\002 \001(" +
      "\005\022\017\n\007y_shift\030\003 \001(\005\022\027\n\017mouse_key_value\030\004 " +
      "\001(\005\022\024\n\014mouse_scroll\030\005 \001(\005\022\026\n\016keyboard_va" +
      "lue\030\006 \001(\005\"\242\001\n\010DataType\022\016\n\nMOUSE_MOVE\020\000\022\025" +
      "\n\021MOUSE_CLICK_PRESS\020\001\022\027\n\023MOUSE_CLICK_REL" +
      "EASE\020\002\022\020\n\014MOUSE_SCROLL\020\003\022\027\n\023KEYBOARD_LON" +
      "G_PRESS\020\004\022\031\n\025KEYBOARD_LONG_RELEASE\020\005\022\020\n\014" +
      "KEYBOARD_HIT\020\006B*\n\026com.baniel.wirelesshid" +
      "B\020WirelessHidProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_HidData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_HidData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_HidData_descriptor,
        new java.lang.String[] { "Type", "XShift", "YShift", "MouseKeyValue", "MouseScroll", "KeyboardValue", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
